name: Validate Types

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: TypeScript check
        run: npx -y tsc --project client/tsconfig.json --noEmit
      - name: Validate sample responses
        run: npm run validate:responses
